name: k6 Load Test na Nuvem

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  k6-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar k6 no ambiente
        uses: grafana/setup-k6-action@v1
        with:
          browser: true

      - name: Executar teste e exportar para Grafana Cloud
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}

          K6_BROWSER_HEADLESS: "true"

          K6_BROWSER_ARGS: "no-sandbox"

          BASE_URL: "https://quickpizza.grafana.com"

        run: |
          k6 run --out cloud index.js

      - name: Upload dos relatórios
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k6-test-report
          path: |
            summary.html
            screenshot.png
          if-no-files-found: warn